   IMGUI_API void DrawBoundingBox(const float* view,
                                  const float* projection,
                                  const float* matrix,
                                  const float* min,
                                  const float* max);
   IMGUI_API void DrawPerspectiveFrustum(const float* view,
                                         const float* projection,
                                         const float* matrix,
                                         const float NearZ,
                                         const float FarZ,
                                         const float width,
                                         const float height,
                                         const float fov);
   IMGUI_API void DrawOrthographicFrustum(const float* view,
                                          const float* projection,
                                          const float* matrix,
                                          const float NearZ,
                                          const float FarZ,
                                          const float width,
                                          const float height);
